import { hasEnvKey } from "../lib/server-utils";
import { isGeminiCliAvailable } from "./model-client";
import type {
  ApprovalRequest,
  BusinessEvent,
  CompanyAccount,
  MissionControlBootstrap,
  MissionAdapterGap,
  MissionAgentLane,
  MissionIntegrationFlow,
  MissionModule,
  MissionOperatingDomain,
  MissionReadModelRecord,
  MissionRollout,
  MissionTask,
  MissionValueLoop,
  RuntimeSurface,
  ServicePosture,
} from "../lib/mission-control";

export const COMPANY_ACCOUNTS: CompanyAccount[] = [
  {
    id: "astro-cleaning-services",
    label: "Astro Cleaning Services",
    shortLabel: "ACS",
    domain: "astrocleanings.com",
    status: "canonical-account",
    sourceOfTruth: "/Users/baileyeubanks/Desktop/Projects/acs/acs-website",
    moduleIds: ["acs-ops", "acs-onboarding", "acs-brand-central"],
    purpose: "Premium cleaning operations: leads, quotes, customers, jobs, crews, dispatch, invoices, and readiness.",
  },
  {
    id: "content-co-op",
    label: "Content Co-op",
    shortLabel: "CCO",
    domain: "contentco-op.com",
    status: "canonical-account",
    sourceOfTruth: "/Users/baileyeubanks/Desktop/Projects/contentco-op/monorepo",
    moduleIds: ["cco-ops", "co-produce", "co-cut", "co-deliver", "cco-brand-central", "aether-video-os"],
    purpose: "Creative business operations: briefs, opportunities, proposals, projects, productions, approvals, delivery, and retainers.",
  },
];

export const MISSION_MODULES: MissionModule[] = [
  {
    id: "acs-ops",
    accountId: "astro-cleaning-services",
    label: "ACS Operations",
    category: "operations",
    status: "extracting",
    authority: "business-model-donor",
    launchPath: "/admin?account=astro-cleaning-services",
    runtimeId: "acs-module-demo",
    description: "Internal ACS lane for quotes, properties, bookings, crews, dispatch, notes, invoices, and follow-up.",
    dependencies: ["ACS public quote intake", "ACS Office action model", "root-2 business objects"],
  },
  {
    id: "cco-ops",
    accountId: "content-co-op",
    label: "Content Co-op Operations",
    category: "operations",
    status: "extracting",
    authority: "business-model-donor",
    launchPath: "/admin?account=content-co-op",
    runtimeId: "cross-business-root-2-donor",
    description: "Creative-business lane for leads, opportunities, clients, projects, approvals, deliverables, billing, and retainers.",
    dependencies: ["CCO creative brief intake", "root-2 project model", "Co-* app rollups"],
  },
  {
    id: "acs-onboarding",
    accountId: "astro-cleaning-services",
    label: "ACS Onboarding",
    category: "support",
    status: "extracting",
    authority: "supporting-subsystem",
    launchPath: "/admin/jobs",
    runtimeId: "acs-onboarding",
    description: "Crew readiness, training progress, certificates, and eligibility signals for ACS dispatch.",
    dependencies: ["astro-cleaning-onboarding donor", "ACS Office training model"],
  },
  {
    id: "co-produce",
    accountId: "content-co-op",
    label: "Co-Produce",
    category: "intelligence",
    status: "extracting",
    authority: "module-demo-donor",
    launchPath: "/admin/files",
    runtimeId: "co-produce",
    description: "Brief-to-production intelligence: scope, timeline, deliverables, scripts, and setup artifacts.",
    dependencies: ["co-produce donors", "Co-Script schema authority"],
  },
  {
    id: "co-cut",
    accountId: "content-co-op",
    label: "Co-Cut",
    category: "delivery",
    status: "external-authority",
    authority: "specialized-app-authority",
    launchPath: "/admin/files",
    runtimeId: "cocut-authority",
    description: "Editorial operator workspace for cuts, revision notes, states, and review preparation.",
    dependencies: ["Desktop Co-Cut app"],
  },
  {
    id: "co-deliver",
    accountId: "content-co-op",
    label: "Co-Deliver",
    category: "delivery",
    status: "external-authority",
    authority: "specialized-app-authority",
    launchPath: "/admin/approvals",
    runtimeId: "codeliver-authority",
    description: "Final review, comments, approvals, packages, delivery clarity, and audit trail.",
    dependencies: ["Desktop Co-Deliver app", "video review backend donor"],
  },
  {
    id: "acs-brand-central",
    accountId: "astro-cleaning-services",
    label: "ACS Brand Central",
    category: "support",
    status: "external-authority",
    authority: "live-public-authority",
    launchPath: "/admin/files",
    runtimeId: null,
    description: "ACS brand and design support surface; not an operational source of truth.",
    dependencies: ["astrocleanings.com/brand-central"],
  },
  {
    id: "cco-brand-central",
    accountId: "content-co-op",
    label: "CCO Brand Central",
    category: "support",
    status: "external-authority",
    authority: "live-public-authority",
    launchPath: "/admin/files",
    runtimeId: null,
    description: "Content Co-op brand and design support surface; separate from operations.",
    dependencies: ["contentco-op.com/brand-central"],
  },
  {
    id: "ai-packets",
    accountId: null,
    label: "AI Packets",
    category: "system",
    status: "active",
    authority: "canonical-shell",
    launchPath: "/admin/packets",
    runtimeId: "mission-control-shell",
    description: "Auditable AI work queue for draft, enrich, summarize, route, retry, cancel, and approve flows.",
    dependencies: ["Packet runtime", "Gemini or local fallback", "operator approval gates"],
  },
  {
    id: "runtime-fleet",
    accountId: null,
    label: "Runtime Fleet",
    category: "system",
    status: "active",
    authority: "canonical-shell",
    launchPath: "/admin/runtime",
    runtimeId: "mission-control-shell",
    description: "Local runtime registry, authority map, port discipline, and deployment freeze visibility.",
    dependencies: ["mission-control-runtime-registry.json", "Mission Control canon"],
  },
  {
    id: "aether-video-os",
    accountId: "content-co-op",
    label: "Aether Video OS",
    category: "intelligence",
    status: "active",
    authority: "canonical-shell",
    launchPath: "/admin/video",
    runtimeId: "mission-control-shell",
    description: "Unified video workspace: Co-Produce, Co-Script, Co-Cut, Co-Deliver with AI agent fleet and real-time collaboration.",
    dependencies: ["Co-Produce donor 4303", "Co-Deliver donor 4304", "Video review backend", "Mission Control shell"],
  },
];

export const MISSION_TASKS: MissionTask[] = [
  {
    id: "task-authority-map",
    accountId: null,
    moduleId: "runtime-fleet",
    title: "Keep authority ledger current",
    status: "in-progress",
    priority: "critical",
    dueState: "now",
    owner: "Codex",
    blocker: null,
    source: "Mission Control Mega Rollout Phase 1",
  },
  {
    id: "task-bootstrap-contract",
    accountId: null,
    moduleId: "ai-packets",
    title: "Maintain shell contracts",
    status: "in-progress",
    priority: "critical",
    dueState: "now",
    owner: "Codex",
    blocker: null,
    source: "Mission Control Mega Rollout Phase 2",
  },
  {
    id: "task-acs-handoff",
    accountId: "astro-cleaning-services",
    moduleId: "acs-ops",
    title: "Convert ACS quote handoffs",
    status: "queued",
    priority: "high",
    dueState: "today",
    owner: "Mission Control",
    blocker: "Do not mutate ACS production path until local shell contract is proven.",
    source: "ACS Module Recovery",
  },
  {
    id: "task-cco-project-rollup",
    accountId: "content-co-op",
    moduleId: "cco-ops",
    title: "Convert CCO brief handoffs",
    status: "queued",
    priority: "high",
    dueState: "today",
    owner: "Mission Control",
    blocker: "Co-* local runtime lanes need smoke proof before integration.",
    source: "Content Co-op Module Recovery",
  },
  {
    id: "task-hermes-demotion",
    accountId: null,
    moduleId: "ai-packets",
    title: "Keep Hermes peripheral",
    status: "done",
    priority: "normal",
    dueState: "today",
    owner: "Mission Control",
    blocker: null,
    source: "AI Operating Model",
  },
  {
    id: "task-video-os-shell",
    accountId: "content-co-op",
    moduleId: "aether-video-os",
    title: "Video OS unified shell",
    status: "in-progress",
    priority: "high",
    dueState: "this-week",
    owner: "Codex",
    blocker: null,
    source: "Aether Video OS v1.0 build",
  },
  {
    id: "task-video-research-integration",
    accountId: "content-co-op",
    moduleId: "aether-video-os",
    title: "Wire Co-Script research into Video OS",
    status: "queued",
    priority: "high",
    dueState: "this-week",
    owner: "Codex",
    blocker: "Co-Produce donor runtime proof on 4303 required first.",
    source: "Aether Video OS v1.0 build",
  },
  {
    id: "task-video-deliver-integration",
    accountId: "content-co-op",
    moduleId: "aether-video-os",
    title: "Wire Co-Deliver into Video OS publish hub",
    status: "queued",
    priority: "normal",
    dueState: "later",
    owner: "Codex",
    blocker: "Co-Deliver donor runtime proof on 4304 required first.",
    source: "Aether Video OS v1.0 build",
  },
];

export const APPROVAL_REQUESTS: ApprovalRequest[] = [
  {
    id: "approval-public-deploy-freeze",
    accountId: null,
    moduleId: "runtime-fleet",
    subject: "Public deploy and domain freeze during local recovery",
    requester: "Mission Control",
    approver: "Founder",
    status: "not-required",
    auditTrail: ["Freeze is active by recovery rule.", "M4/domain work waits for local proof."],
  },
  {
    id: "approval-acs-production-touch",
    accountId: "astro-cleaning-services",
    moduleId: "acs-ops",
    subject: "ACS production changes require production-critical reason",
    requester: "Mission Control",
    approver: "Founder",
    status: "requested",
    auditTrail: ["ACS live authority remains separate.", "No broad ACS edits during shell recovery."],
  },
  {
    id: "approval-paperclip-critical-path",
    accountId: null,
    moduleId: "ai-packets",
    subject: "Paperclip promotion decision",
    requester: "Mission Control",
    approver: "Founder",
    status: "not-required",
    auditTrail: ["Paperclip is optional near-term.", "Revisit after Mission Control shell stabilizes."],
  },
];

export const BUSINESS_EVENTS: BusinessEvent[] = [
  {
    id: "event-canon-lock",
    accountId: null,
    moduleId: "runtime-fleet",
    eventType: "canon.locked",
    title: "Mission Control selected as canonical product",
    summary: "Root demoted to donor/legacy language; one shell with company switching selected.",
    actor: "Codex",
    occurredAt: "2026-04-23T00:00:00.000Z",
    sourceSystem: "MISSION_CONTROL_CANON.md",
  },
  {
    id: "event-runtime-registry",
    accountId: null,
    moduleId: "runtime-fleet",
    eventType: "runtime.registry",
    title: "Local runtime ports assigned",
    summary: "Mission Control uses 4300; module donors use 4301-4306; Platform Relief remains 4317.",
    actor: "Codex",
    occurredAt: "2026-04-23T00:10:00.000Z",
    sourceSystem: "mission-control-runtime-registry.json",
  },
  {
    id: "event-acs-boundary",
    accountId: "astro-cleaning-services",
    moduleId: "acs-ops",
    eventType: "boundary.preserved",
    title: "ACS public intake remains separate",
    summary: "Mission Control consumes ACS intake handoffs but does not own the public quote presentation.",
    actor: "Mission Control",
    occurredAt: "2026-04-23T00:20:00.000Z",
    sourceSystem: "Recovery plan",
  },
  {
    id: "event-cco-boundary",
    accountId: "content-co-op",
    moduleId: "cco-ops",
    eventType: "boundary.preserved",
    title: "Co-* apps remain specialized authorities",
    summary: "Mission Control launches specialist apps from project context and receives rollups instead of rebuilding their internals.",
    actor: "Mission Control",
    occurredAt: "2026-04-23T00:25:00.000Z",
    sourceSystem: "Recovery plan",
  },
];

export const MEGA_ROLLOUT_4: MissionRollout = {
  id: "mega-rollout-4",
  title: "Mega Rollout 4",
  status: "done",
  centerOfGravity: "Downstream proof and adapter readiness",
  summary:
    "Closed as the product spine pass: Mission Control became the verified local hub, with unresolved donor runtime proof carried into Plan 5.",
  workPackets: [
    {
      id: "mr4-runtime-unlock",
      title: "Unlock donor runtime proof",
      status: "blocked",
      owner: "Codex",
      nextAction: "Install donor dependencies only after explicit approval, then re-run runtime proof on 4301-4305.",
      blocker: "Dependency installs require approval and several donor apps have missing node_modules.",
    },
    {
      id: "mr4-acs-path",
      title: "Harden ACS quote-to-job path",
      status: "active",
      owner: "Mission Control",
      nextAction: "Keep ACS quote handoffs visible in Inbox and Jobs with readiness blockers preserved.",
      blocker: null,
    },
    {
      id: "mr4-cco-path",
      title: "Harden CCO brief-to-project path",
      status: "queued",
      owner: "Mission Control",
      nextAction: "Use CCO handoffs to create project candidates and launch Co-Produce or Co-Deliver context.",
      blocker: "Co-* donor lanes still need local runtime proof before deeper wiring.",
    },
    {
      id: "mr4-cloud-signal",
      title: "Evaluate cloud and AI deployment signal",
      status: "parked",
      owner: "Founder + Codex",
      nextAction: "Revisit after local adapter paths and runtime fleet are proven.",
      blocker: "Cloud/provider work waits behind local proof and deployment readiness.",
    },
  ],
  signals: [
    {
      id: "openai-devs-x-2047436655863464011",
      label: "OpenAI Devs Codex signal",
      source: "https://x.com/openaidevs/status/2047436655863464011?s=42",
      status: "parked",
      whenToUse:
        "Use when Mission Control is ready to formalize subagents, app connectors, memory, and repeatable operator automations.",
    },
    {
      id: "google-cloud-tech-x-2047387535383363670",
      label: "Google Cloud Tech signal",
      source: "https://x.com/googlecloudtech/status/2047387535383363670?s=46",
      status: "parked",
      whenToUse:
        "Use when Mission Control is ready to evaluate cloud deployment, managed AI infrastructure, or Google Cloud provider strategy. Do not let it preempt local runtime proof.",
    },
  ],
  acceptance: [
    "Mission Control remains the canonical local shell on 4300.",
    "ACS handoffs remain operable without mutating the public ACS site.",
    "CCO handoffs remain operable without rebuilding Co-* internals.",
    "Runtime proof clearly separates healthy, blocked, and parked lanes.",
    "External cloud signals are parked until local proof is stable.",
  ],
  freeze: [
    "No public deployment",
    "No repo rename",
    "No domain purchase",
    "No Hermes promotion",
    "No Paperclip critical-path dependency",
  ],
};

export const MEGA_VALUE_PLAN_5: MissionRollout = {
  id: "mega-value-plan-5",
  title: "Mega Value Plan 5",
  status: "done",
  centerOfGravity: "Revenue paths and operator leverage",
  summary:
    "Move Mission Control from recovery shell to value engine: prove ACS quote-to-cash, CCO brief-to-delivery, and a daily operator loop without widening scope.",
  workPackets: [
    {
      id: "mvp5-acs-quote-to-cash",
      title: "ACS quote-to-cash",
      status: "active",
      owner: "Mission Control",
      nextAction: "Turn readiness-blocked quote candidates into scheduled work, invoice follow-up, and customer follow-up state.",
      blocker: null,
    },
    {
      id: "mvp5-cco-brief-to-delivery",
      title: "CCO brief-to-delivery",
      status: "queued",
      owner: "Mission Control",
      nextAction: "Convert creative briefs into project candidates, approval rollups, delivery state, and billing follow-up tasks.",
      blocker: "Co-Produce and Co-Deliver runtime lanes still need proof before deeper app wiring.",
    },
    {
      id: "mvp5-daily-operator-loop",
      title: "Daily operator loop",
      status: "active",
      owner: "Founder + Codex",
      nextAction: "Keep Dashboard focused on intake, jobs, runtime proof, active plan, and blockers.",
      blocker: null,
    },
    {
      id: "mvp5-runtime-unblock",
      title: "Runtime unblock queue",
      status: "blocked",
      owner: "Codex",
      nextAction: "Install and smoke donor dependencies only after approval, starting with ACS module and ACS onboarding.",
      blocker: "Dependency installs require explicit approval.",
    },
  ],
  signals: [
    {
      id: "google-cloud-tech-x-2047387535383363670",
      label: "Google Cloud Tech signal",
      source: "https://x.com/googlecloudtech/status/2047387535383363670?s=46",
      status: "parked",
      whenToUse: "Revisit after quote-to-cash, brief-to-delivery, and local runtime proof are stable.",
    },
  ],
  acceptance: [
    "ACS quote handoffs produce visible job, readiness, and follow-up state.",
    "CCO brief handoffs produce visible project, approval, delivery, and billing follow-up state.",
    "Dashboard shows the current value path and blockers without becoming text-heavy.",
    "Runtime blockers remain explicit and do not block shell usability.",
    "No public deployment or cloud/provider jump before local value paths work.",
  ],
  freeze: ["No new shell", "No public deployment", "No repo rename", "No broad donor merge", "No autonomous production mutation"],
};

export const MEGA_VALUE_PLAN_7: MissionRollout = {
  id: "mega-value-plan-7",
  title: "Mega Value Plan 7",
  status: "done",
  centerOfGravity: "Operator value loops",
  summary:
    "Turn Mission Control into a daily operating board: cash path, delivery path, readiness guardrails, and runtime proof all stay visible from one surface.",
  workPackets: [
    {
      id: "mvp7-acs-cash-path",
      title: "ACS cash path",
      status: "active",
      owner: "Mission Control",
      nextAction: "Drive ACS quote handoffs through job candidate, readiness decision, scheduling, invoice, and follow-up.",
      blocker: null,
    },
    {
      id: "mvp7-cco-delivery-path",
      title: "CCO delivery path",
      status: "queued",
      owner: "Mission Control",
      nextAction: "Drive CCO brief handoffs through opportunity, project, approval rollup, delivery state, and billing follow-up.",
      blocker: "Specialist Co-* lanes remain launch-and-rollup surfaces until runtime proof is clean.",
    },
    {
      id: "mvp7-readiness-guardrails",
      title: "Readiness guardrails",
      status: "active",
      owner: "Mission Control",
      nextAction: "Keep crew readiness and approval blockers visible before dispatch, delivery, or external handoff.",
      blocker: null,
    },
    {
      id: "mvp7-proof-ledger",
      title: "Proof ledger",
      status: "blocked",
      owner: "Codex",
      nextAction: "Keep runtime health, missing dependencies, provider config, and no-OAuth local proof visible.",
      blocker: "Donor app dependency installs require explicit approval.",
    },
  ],
  signals: [
    {
      id: "openai-devs-x-2047436655863464011",
      label: "OpenAI Devs Codex signal",
      source: "https://x.com/openaidevs/status/2047436655863464011?s=42",
      status: "parked",
      whenToUse:
        "Use after the operator loops are stable enough to formalize subagents, app connectors, memory, and repeatable automations.",
    },
    {
      id: "google-cloud-tech-x-2047387535383363670",
      label: "Google Cloud Tech signal",
      source: "https://x.com/googlecloudtech/status/2047387535383363670?s=46",
      status: "parked",
      whenToUse: "Use after the local cash path, delivery path, and proof ledger are stable enough to justify infrastructure evaluation.",
    },
  ],
  acceptance: [
    "Dashboard exposes value loops without adding a text-heavy command center.",
    "ACS cash path has a visible route to Inbox, Jobs, Scheduling, and follow-up work.",
    "CCO delivery path has a visible route to Inbox, Approvals, and specialist app launch points.",
    "Readiness and approval blockers stay visible before unsafe operational movement.",
    "Runtime proof remains a blocker ledger, not a reason to create another shell.",
  ],
  freeze: ["No new shell", "No public deployment", "No repo rename", "No cloud jump", "No donor install without approval"],
};

export const MEGA_VALUE_PLAN_8: MissionRollout = {
  id: "mega-value-plan-8",
  title: "Mega Value Plan 8",
  status: "done",
  centerOfGravity: "Agent operating lanes",
  summary:
    "Promote Codex, browser verification, memory/canon, connectors, and subagents into controlled lanes that accelerate Mission Control without becoming unsupervised authority.",
  workPackets: [
    {
      id: "mvp8-codex-patch-lane",
      title: "Codex patch lane",
      status: "active",
      owner: "Codex",
      nextAction: "Keep implementation, tests, runtime proof, and browser verification bundled in one loop.",
      blocker: null,
    },
    {
      id: "mvp8-subagent-lane",
      title: "Subagent lane",
      status: "active",
      owner: "Codex",
      nextAction: "Use parallel agents for bounded sidecar work: UI polish, data contracts, runtime audit, and test repair.",
      blocker: null,
    },
    {
      id: "mvp8-connector-lane",
      title: "Connector lane",
      status: "queued",
      owner: "Mission Control",
      nextAction: "Route Gmail, Drive, Calendar, and future app context through explicit review gates before transmission.",
      blocker: "Sensitive data and third-party actions require action-time confirmation.",
    },
    {
      id: "mvp8-memory-canon-lane",
      title: "Memory and canon lane",
      status: "active",
      owner: "Mission Control",
      nextAction: "Keep prior decisions, rollout history, authority boundaries, and parked signals visible before new work starts.",
      blocker: null,
    },
  ],
  signals: [
    {
      id: "openai-devs-x-2047436655863464011",
      label: "OpenAI Devs Codex signal",
      source: "https://x.com/openaidevs/status/2047436655863464011?s=42",
      status: "ready",
      whenToUse:
        "Use now as the operating-model signal for subagents, connector-aware work, memory-backed recovery, and browser-verified implementation.",
    },
    {
      id: "google-cloud-tech-x-2047387535383363670",
      label: "Google Cloud Tech signal",
      source: "https://x.com/googlecloudtech/status/2047387535383363670?s=46",
      status: "parked",
      whenToUse: "Use after local value loops and agent lanes prove stable enough to justify infrastructure evaluation.",
    },
  ],
  acceptance: [
    "Dashboard shows agent lanes as small actionable cards.",
    "Codex implementation lanes stay tied to tests and browser proof.",
    "Subagents are used only for bounded, non-overlapping sidecar work.",
    "Connector use is gated before sensitive transmission or third-party action.",
    "Memory and canon remain context, not unchecked authority.",
  ],
  freeze: ["No unsupervised production mutation", "No broad connector actions", "No new shell", "No public deploy", "No cloud jump"],
};

export const MEGA_VALUE_PLAN_9: MissionRollout = {
  id: "mega-value-plan-9",
  title: "Mega Value Plan 9",
  status: "done",
  centerOfGravity: "Commercial and dispatch authority",
  summary:
    "Restore the full operating vision: quote/proposal depth, invoice authority, finance ledger separation, and dispatch truth with crew movement and ETA state.",
  workPackets: [
    {
      id: "mvp9-quote-proposal-workspace",
      title: "Quote and proposal workspace",
      status: "active",
      owner: "Mission Control",
      nextAction: "Adopt legacy ROOT quote workflow stages: draft, review, ready to send, sent, accepted, ready to invoice.",
      blocker: null,
    },
    {
      id: "mvp9-invoice-workspace",
      title: "Invoice workspace",
      status: "active",
      owner: "Mission Control",
      nextAction: "Separate invoice authority from finance ledger: issue, collect, remind, reconcile, archive.",
      blocker: null,
    },
    {
      id: "mvp9-dispatch-control",
      title: "Dispatch control",
      status: "active",
      owner: "Mission Control",
      nextAction: "Make crew movement, next stop, ETA, stale ping, geofence, and delay state first-class operator surfaces.",
      blocker: "Live geo tracking waits for canonical dispatch event spine and permissioned mobile capture.",
    },
    {
      id: "mvp9-source-reconciliation",
      title: "Source reconciliation",
      status: "active",
      owner: "Codex",
      nextAction: "Mine legacy ROOT docs, examples, and tests before simplifying or hiding any operational lane.",
      blocker: null,
    },
  ],
  signals: [
    {
      id: "root-quote-invoice-dispatch-contracts",
      label: "Legacy ROOT workflow contracts",
      source: "/Users/baileyeubanks/Desktop/Projects/root",
      status: "ready",
      whenToUse:
        "Use immediately as donor authority for quote/proposal, invoice, and dispatch semantics before building more UI.",
    },
    {
      id: "openai-devs-x-2047436655863464011",
      label: "OpenAI Devs Codex signal",
      source: "https://x.com/openaidevs/status/2047436655863464011?s=42",
      status: "ready",
      whenToUse: "Use for bounded agent lanes after product authority is restored.",
    },
  ],
  acceptance: [
    "Sidebar exposes Quotes, Invoices, Finance, Dispatch, Scheduling, Jobs, and Approvals as distinct lanes.",
    "Quote/proposal workflow is not collapsed into intake or invoices.",
    "Invoice workspace is not confused with finance ledger visibility.",
    "Dispatch is not treated as generic scheduling; it owns crew movement, ETA, route, and geofence truth.",
    "Legacy ROOT docs and examples remain donor authority until Mission Control contracts fully replace them.",
  ],
  freeze: ["No hidden commercial lanes", "No fake geo tracking", "No quote-invoice merge", "No broad production mutation", "No new shell"],
};

export const MEGA_VALUE_PLAN_10: MissionRollout = {
  id: "mega-value-plan-10",
  title: "Mega Value Plan 10",
  status: "done",
  centerOfGravity: "Real integration flows over placeholder shell pages",
  summary:
    "Correct Mission Control against code evidence: ACS and CCO already have real intake/admin flows, Root has the contract spine, and this shell must become the adapter cockpit before it becomes the mutation surface.",
  workPackets: [
    {
      id: "mvp10-operating-domain-model",
      title: "Operating domain model",
      status: "done",
      owner: "Mission Control",
      nextAction: "Use one typed contract for commercial, field, and finance control surfaces.",
      blocker: null,
    },
    {
      id: "mvp10-real-flow-extraction",
      title: "Real flow extraction",
      status: "active",
      owner: "Codex + subagents",
      nextAction: "Promote ACS quote/deposit/job/dispatch and CCO brief/estimate/project/delivery evidence into Mission Control integration flows.",
      blocker: null,
    },
    {
      id: "mvp10-functional-gap-closure",
      title: "Functional gap closure",
      status: "active",
      owner: "Mission Control",
      nextAction: "Replace informational Quotes, Invoices, Dispatch, and Approvals pages with read-only adapters over proven ACS/CCO/Root contracts.",
      blocker: "No send, issue, approve, reject, payment, or live geo mutation until adapter reads are proven.",
    },
    {
      id: "mvp10-cross-app-project-id",
      title: "CCO cross-app project adapter",
      status: "active",
      owner: "Mission Control",
      nextAction: "Define one project/handoff id that carries a public brief into estimate, project, Co-Script, Co-Cut, and Co-Deliver rollups.",
      blocker: "Standalone Co-* apps have real models but no single proven end-to-end project adapter.",
    },
  ],
  signals: [
    {
      id: "root-operating-domain-spine",
      label: "ROOT operating domain spine",
      source: "/Users/baileyeubanks/Desktop/Projects/root",
      status: "ready",
      whenToUse: "Use now to align Mission Control pages to quote, invoice, dispatch, and finance authority boundaries.",
    },
    {
      id: "acs-live-root-admin-flow",
      label: "ACS live ROOT admin flow",
      source: "/Users/baileyeubanks/Desktop/Projects/acs/acs-website",
      status: "ready",
      whenToUse: "Use now for quote engine, paid deposit, job handoff, admin quotes, invoices, crew portal, GPS, ETA, and dispatch truth.",
    },
    {
      id: "cco-root-commercial-flow",
      label: "CCO Root commercial flow",
      source: "/Users/baileyeubanks/Desktop/Projects/contentco-op/monorepo/apps/home",
      status: "ready",
      whenToUse: "Use now for creative brief, estimates, approvals, projects, deliverables, Co-* launch and rollup work.",
    },
    {
      id: "cco-proposal-training-data",
      label: "CCO proposal quote invoice training data",
      source: "/Users/baileyeubanks/Downloads/CCO_PROPOSAL:QUOTE:INVOICE_ TRAINING DATA",
      status: "parked",
      whenToUse: "Use after the contract-backed quote and invoice pages exist, so training artifacts map into the right lifecycle.",
    },
  ],
  acceptance: [
    "Mission Control names the real ACS quote-to-job-to-dispatch flow with code-backed producer and consumer files.",
    "Mission Control names the real CCO brief-to-estimate-to-project-to-delivery flow with code-backed producer and consumer files.",
    "Mission Control admits current functional gaps instead of representing informational cards as working modules.",
    "Root workflow contracts remain the mutation spine until adapters prove safe replacements.",
    "Platform Relief/pro-se.info remains separate-business context, not blended into ACS/CCO.",
  ],
  freeze: ["No fake functional pages", "No send/issue buttons yet", "No live geo capture yet", "No production schema mutation", "No cross-app merge without adapter proof"],
};

export const MEGA_VALUE_PLAN_11: MissionRollout = {
  id: "mega-value-plan-11",
  title: "Mega Value Plan 11",
  status: "active",
  centerOfGravity: "Read-only adapter spine before mutation",
  summary:
    "Convert the deeper repo evidence into a visible gap ledger so Mission Control stops pretending missing tabs are product choices. The next real build is read models for quote, proposal, invoice, dispatch, CCO project, and brand boundaries before any send, approve, issue, payment, or live geo action.",
  workPackets: [
    {
      id: "mvp11-acs-commercial-adapter",
      title: "ACS commercial adapter",
      status: "active",
      owner: "Mission Control",
      nextAction: "Read ACS quote, deposit, booking, invoice, and ROOT handoff state into Quotes, Inbox, Jobs, and Invoices.",
      blocker: "No write controls until ACS public authority and Root contract mapping are proven together.",
    },
    {
      id: "mvp11-acs-dispatch-adapter",
      title: "ACS dispatch adapter",
      status: "active",
      owner: "Mission Control",
      nextAction: "Read route plans, crew assignment, latest ping, geofence, stale ping, ETA, and delay state into Dispatch.",
      blocker: "Live geo capture and customer ETA messaging require permissioned mobile/event spine first.",
    },
    {
      id: "mvp11-cco-commercial-adapter",
      title: "CCO commercial adapter",
      status: "active",
      owner: "Mission Control",
      nextAction: "Read creative briefs, estimates, approvals, project candidates, delivery rollups, and billing follow-up.",
      blocker: "No estimate send, approval decision, invoice issue, or Co-* mutation until cross-app id is proven.",
    },
    {
      id: "mvp11-root-contract-adoption",
      title: "Root contract adoption",
      status: "active",
      owner: "Codex",
      nextAction: "Mirror or import Root quote, proposal, invoice, approval, dispatch, job, billing, and work-claim schemas.",
      blocker: "Current shell still uses simplified TypeScript contracts that cannot safely drive real operations.",
    },
  ],
  signals: [
    {
      id: "acs-deep-context",
      label: "ACS quote, invoice, dispatch proof",
      source: "/Users/baileyeubanks/Desktop/Projects/acs/acs-website",
      status: "ready",
      whenToUse: "Use now to replace static ACS placeholders with read-only operational truth.",
    },
    {
      id: "cco-deep-context",
      label: "CCO brief, estimate, Co-* proof",
      source: "/Users/baileyeubanks/Desktop/Projects/contentco-op",
      status: "ready",
      whenToUse: "Use now to wire brief-to-project rollups without rebuilding specialist apps inside Mission Control.",
    },
    {
      id: "brand-prose-boundary-context",
      label: "Brand and pro-se boundary",
      source: "/Users/baileyeubanks/Desktop/Projects/brand",
      status: "ready",
      whenToUse: "Use now to keep Brand Central as support authority and pro-se.info as a separate business lane.",
    },
  ],
  acceptance: [
    "Dashboard shows the highest-value adapter gaps without adding a text-heavy planning wall.",
    "ACS quote, invoice, dispatch, and readiness gaps are explicit and routed to the correct admin pages.",
    "CCO brief, estimate, project, Co-*, approval, and billing gaps are explicit.",
    "Root contracts are identified as the mutation authority before Mission Control exposes write controls.",
    "Brand Central and pro-se.info remain correctly bounded instead of blurred into ACS/CCO operations.",
  ],
  freeze: [
    "No send/approve/issue/payment controls",
    "No live geo capture",
    "No production schema mutation",
    "No Co-* rebuild inside Mission Control",
    "No pro-se blend into ACS/CCO",
  ],
};

export const MEGA_VALUE_PLAN_12: MissionRollout = {
  id: "mega-value-plan-12",
  title: "Mega Value Plan 12",
  status: "queued",
  centerOfGravity: "Operational read models on core pages",
  summary:
    "Promote the adapter gap ledger into read-only operating records. Quotes, invoices, dispatch, and CCO project flow should show the real work objects Mission Control is trying to control before any mutation or automation is exposed.",
  workPackets: [
    {
      id: "mvp12-domain-read-models",
      title: "Domain read models",
      status: "active",
      owner: "Mission Control",
      nextAction: "Render quote, invoice, dispatch, and CCO project records directly on their operating pages.",
      blocker: null,
    },
    {
      id: "mvp12-acs-quote-to-cash-fixture",
      title: "ACS quote-to-cash fixture",
      status: "active",
      owner: "Mission Control",
      nextAction: "Carry the ACS quote handoff through quote, readiness, job candidate, invoice, and follow-up state as read-only records.",
      blocker: "Production ACS writes remain closed.",
    },
    {
      id: "mvp12-dispatch-fixture",
      title: "Dispatch snapshot fixture",
      status: "active",
      owner: "Mission Control",
      nextAction: "Expose route, crew, next stop, ETA, stale ping, geofence, and delay truth as a dispatch snapshot.",
      blocker: "Live GPS capture remains off.",
    },
    {
      id: "mvp12-cco-project-spine",
      title: "CCO project spine fixture",
      status: "active",
      owner: "Mission Control",
      nextAction: "Show the missing cross-app project id as an explicit adapter-needed read model.",
      blocker: "No Co-* write context until the shared project key exists.",
    },
  ],
  signals: [
    {
      id: "mvp12-core-pages",
      label: "Core operating pages",
      source: "/admin/quotes /admin/invoices /admin/dispatch",
      status: "ready",
      whenToUse: "Use now to visually verify Mission Control is carrying real records instead of only plan cards.",
    },
    {
      id: "mvp12-root-mutation-gates",
      label: "Root mutation gates",
      source: "/Users/baileyeubanks/Desktop/Projects/root/src",
      status: "ready",
      whenToUse: "Use before enabling any send, approve, issue, dispatch, or payment action.",
    },
  ],
  acceptance: [
    "Quotes page shows ACS quote-to-cash and CCO estimate records.",
    "Invoices page shows invoice continuation records separate from Finance ledger.",
    "Dispatch page shows a route/crew/ETA/geofence snapshot, not generic scheduling copy.",
    "Each record lists mutation gates so unsafe controls stay visibly closed.",
    "CCO project spine remains adapter-needed until the shared project id is real.",
  ],
  freeze: [
    "No production writes",
    "No send/approve/issue/payment buttons",
    "No live GPS capture",
    "No Co-* write launch",
    "No fake completed adapter status",
  ],
};

export const MISSION_OPERATING_DOMAINS: MissionOperatingDomain[] = [
  {
    id: "quotes",
    title: "Quotes & Proposals",
    route: "/admin/quotes",
    status: "contract-backed",
    purpose: "Shape negotiable commercial scope, pricing, terms, approval, client send readiness, and quote-to-invoice conversion.",
    authority: "Shared quote lifecycle after ACS or CCO public intake handoff.",
    doesNotOwn: "Public intake UI, payment collection, invoice truth, or finance reconciliation.",
    lifecycle: ["Handoff", "Draft", "Needs review", "Ready to send", "Sent", "Accepted", "Ready to invoice"],
    sourceDocs: [
      "/Users/baileyeubanks/Desktop/Projects/root/QUOTE_WORKFLOW.md",
      "/Users/baileyeubanks/Desktop/Projects/root/QUOTE_INVOICE_OPERATION_RULES.md",
    ],
    nextAction: "Promote quote workflow examples into local read models before adding draft mutation controls.",
    blocker: null,
  },
  {
    id: "invoices",
    title: "Invoices",
    route: "/admin/invoices",
    status: "contract-backed",
    purpose: "Own billing authority after approved quote conversion or direct invoice creation.",
    authority: "Invoice numbering, issue state, artifacts, payment awareness, reminders, closeout, and archive gate.",
    doesNotOwn: "Negotiable proposal shaping, public checkout UI, or accounting ledger reconciliation by itself.",
    lifecycle: ["Draft", "Internal review", "Approved to issue", "Issued", "Partial", "Paid", "Reconciled", "Archived"],
    sourceDocs: [
      "/Users/baileyeubanks/Desktop/Projects/root/INVOICE_WORKFLOW.md",
      "/Users/baileyeubanks/Desktop/Projects/root/QUOTE_INVOICE_OPERATION_RULES.md",
    ],
    nextAction: "Separate invoice workspace fixtures from Finance ledger rows, then wire quote conversion read models.",
    blocker: null,
  },
  {
    id: "dispatch",
    title: "Dispatch",
    route: "/admin/dispatch",
    status: "contract-backed",
    purpose: "Track real operational route truth: crew movement, route state, next stop, ETA, stale ping, geofence, and delay state.",
    authority: "Shared dispatch truth after schedule handoff, before any customer timing message is proposed.",
    doesNotOwn: "Public booking, raw mobile telemetry permissions, customer message sending, or generic schedule planning.",
    lifecycle: ["Planned", "Staged", "Departed office", "En route", "Approaching", "Onsite", "Complete", "Closed"],
    sourceDocs: ["/Users/baileyeubanks/Desktop/Projects/root/DISPATCH_CONTROL.md"],
    nextAction: "Create a local dispatch snapshot fixture with route, next stop, ETA, geofence, and delay fields.",
    blocker: "Live geo tracking waits for permissioned mobile capture and dispatch event persistence.",
  },
  {
    id: "finance",
    title: "Finance",
    route: "/admin/finance",
    status: "ledger",
    purpose: "Expose finance visibility, reconciliation, overdue risk, collected totals, and archive readiness.",
    authority: "Ledger and reconciliation visibility after invoices are issued, paid, voided, or exceptioned.",
    doesNotOwn: "Quote drafting, invoice issue authority, payment processor truth, or document generation.",
    lifecycle: ["Not visible", "Visible", "Reconciling", "Reconciled", "Exception", "Archived"],
    sourceDocs: ["/Users/baileyeubanks/Desktop/Projects/root/INVOICE_WORKFLOW.md"],
    nextAction: "Keep Finance tied to invoice outputs but separate from invoice authoring and issue controls.",
    blocker: null,
  },
];

export const MISSION_INTEGRATION_FLOWS: MissionIntegrationFlow[] = [
  {
    id: "acs-public-quote-to-root-dispatch",
    accountId: "astro-cleaning-services",
    title: "ACS quote engine to ROOT dispatch",
    status: "real-flow",
    sourceSurface: "astrocleanings.com quote engine and public booking checkout",
    adminSurface: "ACS ROOT admin plus Mission Control ACS ops",
    contractAuthority:
      "ACS public intake contract plus Desktop Root quote, invoice, job, dispatch, approval, and billing-event contracts.",
    actualStages: [
      "Browser quote UI calculates canonical pricing payload",
      "submitQuote upserts contact, quote, quote_items, and handoff payload",
      "public checkout validates quote lifecycle and availability",
      "slot reservation holds appointment window",
      "Stripe deposit checkout records deposit handoff",
      "recordPublicBookingIntent finalizes ROOT-owned job state",
      "crew portal receives assignments and posts GPS pings",
      "dispatch consumes route plans, job_locations, geofence departure, ETA, and customer tracking state",
    ],
    producerFiles: [
      "/Users/baileyeubanks/Desktop/Projects/acs/acs-website/js/quote-engine.js",
      "/Users/baileyeubanks/Desktop/Projects/acs/acs-website/js/acs-quote-core.js",
      "/Users/baileyeubanks/Desktop/Projects/acs/acs-website/api/functions/submitQuote.js",
      "/Users/baileyeubanks/Desktop/Projects/acs/acs-website/api/functions/_acsIntakeContract.js",
      "/Users/baileyeubanks/Desktop/Projects/acs/acs-website/api/functions/createPublicDepositCheckout.js",
      "/Users/baileyeubanks/Desktop/Projects/acs/acs-website/api/functions/recordPublicBookingIntent.js",
      "/Users/baileyeubanks/Desktop/Projects/acs/acs-website/api/functions/crewReportLocation.js",
    ],
    consumerFiles: [
      "/Users/baileyeubanks/Desktop/Projects/acs/acs-website/api/functions/adminQuotes.js",
      "/Users/baileyeubanks/Desktop/Projects/acs/acs-website/api/functions/adminInvoices.js",
      "/Users/baileyeubanks/Desktop/Projects/acs/acs-website/api/functions/root.js",
      "/Users/baileyeubanks/Desktop/Projects/acs/acs-website/app/src/pages/RootQuotesPage.jsx",
      "/Users/baileyeubanks/Desktop/Projects/acs/acs-website/app/src/pages/RootDispatchPage.jsx",
      "/Users/baileyeubanks/Desktop/Projects/root/src/quote-workflow/contracts.ts",
      "/Users/baileyeubanks/Desktop/Projects/root/src/dispatch-control/contracts.ts",
    ],
    missingAdapter:
      "Mission Control needs a read-only adapter over ACS quote, booking, job, invoice, route, GPS, and ETA records before it adds mutation controls.",
    nextAction:
      "Replace /admin/quotes and /admin/dispatch placeholders with ACS-backed read models for quote lifecycle, booking status, crew route, latest ping, geofence, and ETA.",
    route: "/admin/quotes",
  },
  {
    id: "cco-brief-to-commercial-project-delivery",
    accountId: "content-co-op",
    title: "CCO creative brief to project and delivery",
    status: "partially-wired",
    sourceSurface: "contentco-op.com /brief",
    adminSurface: "Content Co-op Root admin plus specialist Co-* apps",
    contractAuthority:
      "CCO Root commercial pipeline plus Desktop Root quote/proposal/invoice/approval/project contracts.",
    actualStages: [
      "Public /brief writes creative_briefs and structured handoff payload",
      "brief_submitted event and orchestrator/Hermes handoff are emitted",
      "Root creates estimate and legacy quote bridge row",
      "approval gates control estimate send and decision",
      "approved estimate creates deposit invoice or waiver path",
      "brief converts into projects and deliverables",
      "Co-Script supports scripts, frameworks, research, and AI generation",
      "Co-Cut handles edit snapshots and export",
      "Co-Deliver handles review tokens, comments, approvals, versions, and delivery audit",
    ],
    producerFiles: [
      "/Users/baileyeubanks/Desktop/Projects/contentco-op/monorepo/apps/home/app/brief/brief-client.tsx",
      "/Users/baileyeubanks/Desktop/Projects/contentco-op/monorepo/apps/home/app/api/briefs/route.ts",
      "/Users/baileyeubanks/Desktop/Projects/contentco-op/monorepo/apps/home/lib/creative-brief.ts",
      "/Users/baileyeubanks/Desktop/Projects/contentco-op/monorepo/apps/home/lib/root-commercial-pipeline.ts",
      "/Users/baileyeubanks/Desktop/Projects/contentco-op/monorepo/apps/home/lib/root-projects-engine.ts",
    ],
    consumerFiles: [
      "/Users/baileyeubanks/Desktop/Projects/contentco-op/monorepo/apps/home/app/api/root/briefs/[id]/estimates/route.ts",
      "/Users/baileyeubanks/Desktop/Projects/contentco-op/monorepo/apps/home/app/api/root/briefs/[id]/convert/route.ts",
      "/Users/baileyeubanks/Desktop/Projects/contentco-op/coscript/app/api/scripts/route.ts",
      "/Users/baileyeubanks/Desktop/Projects/contentco-op/cocut/src/services/projectService.ts",
      "/Users/baileyeubanks/Desktop/Projects/contentco-op/codeliver/app/api/review/[token]/route.ts",
      "/Users/baileyeubanks/Desktop/Projects/root/src/proposal-workflow/contracts.ts",
      "/Users/baileyeubanks/Desktop/Projects/root/src/approval-workflow/contracts.ts",
    ],
    missingAdapter:
      "There is no single canonical cross-app project id carrying brief -> estimate -> project -> script -> edit -> deliver assets.",
    nextAction:
      "Define and render the CCO project adapter spine before rebuilding Co-Produce/Co-Cut/Co-Deliver inside Mission Control.",
    route: "/admin/inbox",
  },
  {
    id: "brand-authority-to-brand-central-mirrors",
    accountId: "content-co-op",
    title: "Brand authority to Brand Central mirrors",
    status: "real-flow",
    sourceSurface: "/Users/baileyeubanks/Desktop/Projects/brand",
    adminSurface: "ACS and CCO Brand Central support surfaces",
    contractAuthority: "Brand repo tokens, themes, Brand OS docs, and sync-authority script.",
    actualStages: [
      "Brand repo owns shared ACS, CCO, Root, and Co-* design authority",
      "sync-authority copies tokens, themes, adapters, and Brand Central HTML",
      "ACS serves static /brandcentral and /brandcentral/root",
      "CCO serves /brandcentral and compatibility /brandcenter redirects",
      "Mission Control links to these as support surfaces, not operational sources of truth",
    ],
    producerFiles: [
      "/Users/baileyeubanks/Desktop/Projects/brand/scripts/sync-authority.mjs",
      "/Users/baileyeubanks/Desktop/Projects/brand/tokens/primitives.json",
      "/Users/baileyeubanks/Desktop/Projects/brand/tokens/semantic.json",
      "/Users/baileyeubanks/Desktop/Projects/brand/themes/themes.json",
    ],
    consumerFiles: [
      "/Users/baileyeubanks/Desktop/Projects/acs/acs-website/brandcentral/index.html",
      "/Users/baileyeubanks/Desktop/Projects/acs/acs-website/brandcentral/root/index.html",
      "/Users/baileyeubanks/Desktop/Projects/contentco-op/monorepo/apps/home/app/brandcentral/route.ts",
      "/Users/baileyeubanks/Desktop/Projects/contentco-op/monorepo/apps/home/app/brandcenter/route.ts",
    ],
    missingAdapter: null,
    nextAction: "Keep Brand Central out of operations while linking it from Files/Support and using Brand repo as the only token authority.",
    route: "/admin/files",
  },
  {
    id: "pro-se-info-platform-relief",
    accountId: "pro-se-info",
    title: "pro-se.info / Platform Relief",
    status: "separate-business",
    sourceSurface: "pro-se.info private beta",
    adminSurface: "Platform Relief runtime on 4317",
    contractAuthority: "/Users/baileyeubanks/Downloads/platform-relief",
    actualStages: [
      "Public beta limited to Texas platform account dispute lane",
      "Routes cover intake, acknowledgement, matter overview, timeline, evidence, and workflow",
      "Payment, settings, dashboard, and hidden matter routes are intentionally redirected or constrained",
      "No code evidence ties this product into ACS, CCO, Root business_unit, or Brand repo authority",
    ],
    producerFiles: [
      "/Users/baileyeubanks/Downloads/platform-relief/src/routes/public/LandingPage.tsx",
      "/Users/baileyeubanks/Downloads/platform-relief/src/pages/IntakeWizard.tsx",
      "/Users/baileyeubanks/Downloads/platform-relief/src/config/publicBeta.ts",
      "/Users/baileyeubanks/Downloads/platform-relief/src/App.tsx",
    ],
    consumerFiles: ["/Users/baileyeubanks/Downloads/platform-relief/server.ts"],
    missingAdapter: "None for ACS/CCO. Only add later as a deliberate third tenant or separate Mission Control account.",
    nextAction: "Preserve as separate business context; do not blend into ACS/CCO recovery work.",
    route: "/admin/runtime",
  },
];

export const MISSION_ADAPTER_GAPS: MissionAdapterGap[] = [
  {
    id: "acs-quote-admin-read-adapter",
    accountId: "astro-cleaning-services",
    title: "ACS quote and invoice read adapter",
    status: "read-only-next",
    sourceFlowId: "acs-public-quote-to-root-dispatch",
    affectedRoutes: ["/admin/inbox", "/admin/quotes", "/admin/invoices", "/admin/jobs"],
    requiredReadModel: [
      "quote lifecycle",
      "contact and service address",
      "quote_items and pricing sections",
      "deposit checkout status",
      "booking confirmation",
      "invoice and follow-up state",
      "ROOT handoff payload",
    ],
    requiredMutationGate: [
      "draft quote edits",
      "send quote",
      "convert to job",
      "issue invoice",
      "send payment reminder",
    ],
    proofFiles: [
      "/Users/baileyeubanks/Desktop/Projects/acs/acs-website/api/functions/submitQuote.js",
      "/Users/baileyeubanks/Desktop/Projects/acs/acs-website/api/functions/adminQuotes.js",
      "/Users/baileyeubanks/Desktop/Projects/acs/acs-website/api/functions/adminInvoices.js",
      "/Users/baileyeubanks/Desktop/Projects/acs/acs-website/api/functions/_acsIntakeContract.js",
      "/Users/baileyeubanks/Desktop/Projects/root/src/quote-workflow/contracts.ts",
      "/Users/baileyeubanks/Desktop/Projects/root/src/invoice-workflow/contracts.ts",
    ],
    nextAction:
      "Build the ACS quote read model first, then expose invoice state as a linked read-only continuation instead of a fake invoice workspace.",
    blocker: null,
  },
  {
    id: "acs-dispatch-geo-read-adapter",
    accountId: "astro-cleaning-services",
    title: "ACS dispatch and geo read adapter",
    status: "read-only-next",
    sourceFlowId: "acs-public-quote-to-root-dispatch",
    affectedRoutes: ["/admin/dispatch", "/admin/scheduling", "/admin/jobs", "/admin/health"],
    requiredReadModel: [
      "crew_members",
      "job_crew_assignments",
      "daily_route_plans",
      "schedule_progress",
      "job_locations",
      "latest crew ping",
      "geofence departure",
      "ETA and delay state",
    ],
    requiredMutationGate: [
      "dispatch crew",
      "start live location capture",
      "send customer ETA",
      "override route",
      "mark arrival or completion",
    ],
    proofFiles: [
      "/Users/baileyeubanks/Desktop/Projects/acs/acs-website/crew-portal.html",
      "/Users/baileyeubanks/Desktop/Projects/acs/acs-website/api/functions/crewReportLocation.js",
      "/Users/baileyeubanks/Desktop/Projects/acs/acs-website/api/functions/root.js",
      "/Users/baileyeubanks/Desktop/Projects/acs/acs-website/supabase/migrations/20260225_job_locations.sql",
      "/Users/baileyeubanks/Desktop/Projects/acs/acs-website/supabase/migrations/20260226_postgis_tracking.sql",
      "/Users/baileyeubanks/Desktop/Projects/root/src/dispatch-control/contracts.ts",
    ],
    nextAction: "Render a real dispatch snapshot from existing ACS route and geo concepts before adding any live map or mobile writes.",
    blocker: "Permissioned mobile capture and customer-facing ETA messaging must remain off until event persistence is canonical.",
  },
  {
    id: "cco-brief-commercial-read-adapter",
    accountId: "content-co-op",
    title: "CCO brief, estimate, and approval adapter",
    status: "read-only-next",
    sourceFlowId: "cco-brief-to-commercial-project-delivery",
    affectedRoutes: ["/admin/inbox", "/admin/quotes", "/admin/approvals", "/admin/invoices"],
    requiredReadModel: [
      "creative_briefs",
      "structured brief fields",
      "estimate payload",
      "legacy quote bridge",
      "approval gates",
      "client decision",
      "deposit invoice or waiver",
      "ready_to_schedule state",
    ],
    requiredMutationGate: [
      "send estimate",
      "approve or reject estimate",
      "convert to project",
      "create deposit invoice",
      "send billing follow-up",
    ],
    proofFiles: [
      "/Users/baileyeubanks/Desktop/Projects/contentco-op/monorepo/apps/home/app/api/briefs/route.ts",
      "/Users/baileyeubanks/Desktop/Projects/contentco-op/monorepo/apps/home/app/api/root/briefs/[id]/estimates/route.ts",
      "/Users/baileyeubanks/Desktop/Projects/contentco-op/monorepo/apps/home/app/api/root/briefs/[id]/convert/route.ts",
      "/Users/baileyeubanks/Desktop/Projects/contentco-op/monorepo/apps/home/lib/root-commercial-pipeline.ts",
      "/Users/baileyeubanks/Desktop/Projects/root/src/proposal-workflow/contracts.ts",
      "/Users/baileyeubanks/Desktop/Projects/root/src/approval-workflow/contracts.ts",
    ],
    nextAction:
      "Make CCO briefs appear as commercial read models with estimate and approval state before exposing proposal or invoice actions.",
    blocker: null,
  },
  {
    id: "cco-cross-app-project-adapter",
    accountId: "content-co-op",
    title: "CCO cross-app project id adapter",
    status: "missing",
    sourceFlowId: "cco-brief-to-commercial-project-delivery",
    affectedRoutes: ["/admin/inbox", "/admin/files", "/admin/approvals"],
    requiredReadModel: [
      "brief id",
      "project id",
      "Co-Script script id",
      "Co-Cut project snapshot",
      "Co-Deliver review asset id",
      "approval and delivery rollup",
      "billing follow-up task",
    ],
    requiredMutationGate: [
      "launch Co-Produce with write context",
      "create Co-Cut project",
      "create Co-Deliver package",
      "approve delivery",
      "final handoff",
    ],
    proofFiles: [
      "/Users/baileyeubanks/Desktop/Projects/contentco-op/coscript/supabase/migrations/001_coscript_schema.sql",
      "/Users/baileyeubanks/Desktop/Projects/contentco-op/cocut/src/services/projectService.ts",
      "/Users/baileyeubanks/Desktop/Projects/contentco-op/cocut/src/services/supabaseProjectService.ts",
      "/Users/baileyeubanks/Desktop/Projects/contentco-op/codeliver/supabase/migrations/001_codeliver_schema.sql",
      "/Users/baileyeubanks/Desktop/Projects/contentco-op/codeliver/app/api/review/[token]/route.ts",
    ],
    nextAction: "Define one Mission Control project adapter id that can carry a brief through estimate, project, edit, review, and delivery.",
    blocker: "Standalone Co-* apps have useful schemas but no proven shared cross-app project key yet.",
  },
  {
    id: "root-contract-adoption-gap",
    accountId: null,
    title: "Root workflow contract adoption",
    status: "blocked",
    sourceFlowId: null,
    affectedRoutes: ["/admin/quotes", "/admin/invoices", "/admin/dispatch", "/admin/approvals", "/admin/finance"],
    requiredReadModel: [
      "quote workflow contract",
      "proposal workflow contract",
      "invoice workflow contract",
      "approval workflow contract",
      "dispatch control contract",
      "job workflow contract",
      "billing event provenance",
      "work claim and handoff lifecycle",
    ],
    requiredMutationGate: [
      "all quote writes",
      "all proposal writes",
      "all invoice issue actions",
      "all approval decisions",
      "all dispatch writes",
      "all billing event writes",
    ],
    proofFiles: [
      "/Users/baileyeubanks/Desktop/Projects/root/src/quote-workflow/contracts.ts",
      "/Users/baileyeubanks/Desktop/Projects/root/src/proposal-workflow/contracts.ts",
      "/Users/baileyeubanks/Desktop/Projects/root/src/invoice-workflow/contracts.ts",
      "/Users/baileyeubanks/Desktop/Projects/root/src/approval-workflow/contracts.ts",
      "/Users/baileyeubanks/Desktop/Projects/root/src/dispatch-control/contracts.ts",
      "/Users/baileyeubanks/Desktop/Projects/root/src/work-claims/contracts.ts",
      "/Users/baileyeubanks/Desktop/Projects/root/src/billing-events/contracts.ts",
    ],
    nextAction: "Create a Mission Control contract mirror or import boundary before any page exposes real operational mutations.",
    blocker: "Current Mission Control shell contracts are intentionally simplified recovery types.",
  },
  {
    id: "brand-prose-boundary-gap",
    accountId: "pro-se-info",
    title: "Brand Central and pro-se boundary",
    status: "parked",
    sourceFlowId: "brand-authority-to-brand-central-mirrors",
    affectedRoutes: ["/admin/files", "/admin/runtime"],
    requiredReadModel: [
      "Brand repo token and theme authority",
      "ACS Brand Central mirror",
      "CCO Brand Central mirror",
      "Platform Relief runtime status",
      "separate-business lane marker",
    ],
    requiredMutationGate: [
      "brand token sync",
      "Brand Central publish",
      "pro-se tenant promotion",
      "Platform Relief deployment",
    ],
    proofFiles: [
      "/Users/baileyeubanks/Desktop/Projects/brand/scripts/sync-authority.mjs",
      "/Users/baileyeubanks/Desktop/Projects/brand/tokens/primitives.json",
      "/Users/baileyeubanks/Desktop/Projects/acs/acs-website/brandcentral/index.html",
      "/Users/baileyeubanks/Desktop/Projects/contentco-op/monorepo/apps/home/app/brandcentral/route.ts",
      "/Users/baileyeubanks/Downloads/platform-relief/src/config/publicBeta.ts",
    ],
    nextAction: "Keep Brand Central visible as support context and preserve pro-se.info as separate-business until intentionally promoted.",
    blocker: "No evidence yet that pro-se.info belongs inside the ACS/CCO Mission Control account model.",
  },
];

export const MISSION_READ_MODELS: MissionReadModelRecord[] = [
  {
    id: "readmodel-acs-quote-to-cash",
    accountId: "astro-cleaning-services",
    domainId: "quotes",
    title: "Maya Thompson quote to job candidate",
    entityKind: "quote",
    lifecycleStage: "Handoff -> Readiness blocked",
    status: "read-only",
    sourceFlowId: "acs-public-quote-to-root-dispatch",
    sourceSystem: "ACS quote engine + local Mission Control handoff",
    dataSource: "mixed",
    owner: "ACS Operations",
    route: "/admin/inbox",
    amountLabel: "Quote pending",
    facts: [
      "Public quote intake is the producer; Mission Control consumes the handoff.",
      "Readiness blocks assignment until a deep-clean certified crew is eligible.",
      "Quote, job candidate, invoice follow-up, and dispatch readiness are one operating chain.",
    ],
    mutationGates: ["edit quote", "send quote", "convert to job", "assign crew", "issue invoice"],
    nextAction: "Replace this fixture with the ACS quote read adapter over quote, quote_items, booking, and handoff payload records.",
    blocker: "Deep-clean certified crew required before dispatch.",
  },
  {
    id: "readmodel-cco-brief-estimate",
    accountId: "content-co-op",
    domainId: "quotes",
    title: "Northstar Logistics creative brief estimate",
    entityKind: "quote",
    lifecycleStage: "Brief -> Estimate candidate",
    status: "adapter-needed",
    sourceFlowId: "cco-brief-to-commercial-project-delivery",
    sourceSystem: "Content Co-op /brief + Root commercial pipeline",
    dataSource: "static_recovery_contract",
    owner: "CCO Operations",
    route: "/admin/inbox?account=content-co-op",
    amountLabel: "Estimate pending",
    facts: [
      "Creative brief writes structured intake and starts commercial workflow.",
      "Estimate, quote bridge, approval gate, and deposit invoice are separate states.",
      "Mission Control should roll up the commercial state without becoming the specialist production app.",
    ],
    mutationGates: ["send estimate", "approve estimate", "convert to project", "create deposit invoice"],
    nextAction: "Build a CCO commercial read adapter over creative_briefs, estimates, approvals, and commercial workflow rows.",
    blocker: "Cross-app project id still missing.",
  },
  {
    id: "readmodel-acs-invoice-continuation",
    accountId: "astro-cleaning-services",
    domainId: "invoices",
    title: "ACS invoice continuation after accepted quote",
    entityKind: "invoice",
    lifecycleStage: "Ready to invoice",
    status: "adapter-needed",
    sourceFlowId: "acs-public-quote-to-root-dispatch",
    sourceSystem: "ACS adminInvoices + Root invoice contract",
    dataSource: "static_recovery_contract",
    owner: "Billing",
    route: "/admin/invoices",
    amountLabel: "Not issued",
    facts: [
      "Invoice authority starts after quote acceptance or direct billable work.",
      "Finance ledger visibility is downstream of invoice issue and payment state.",
      "Invoice reminders are gated communications, not automatic sends.",
    ],
    mutationGates: ["create invoice", "issue invoice", "send reminder", "mark paid", "archive invoice"],
    nextAction: "Wire invoice read models to ACS admin invoice rows and Root invoice lifecycle before adding issue controls.",
    blocker: "Quote-to-invoice conversion adapter not yet implemented.",
  },
  {
    id: "readmodel-cco-deposit-invoice",
    accountId: "content-co-op",
    domainId: "invoices",
    title: "CCO deposit invoice after approved estimate",
    entityKind: "invoice",
    lifecycleStage: "Approved estimate -> Deposit path",
    status: "adapter-needed",
    sourceFlowId: "cco-brief-to-commercial-project-delivery",
    sourceSystem: "CCO Root commercial pipeline + Root invoice contract",
    dataSource: "static_recovery_contract",
    owner: "CCO Billing",
    route: "/admin/approvals",
    amountLabel: "Deposit pending",
    facts: [
      "Estimate approval can create a deposit invoice or waiver path.",
      "Billing follow-up should become a Mission Control task after approval.",
      "Delivery and billing state must be rolled up from specialist apps, not reimplemented here.",
    ],
    mutationGates: ["approve deposit path", "create invoice", "send payment link", "waive deposit"],
    nextAction: "Read approved estimate and deposit/waiver state into Invoices without issuing anything from Mission Control yet.",
    blocker: "Approval decision adapter still read-only.",
  },
  {
    id: "readmodel-acs-dispatch-snapshot",
    accountId: "astro-cleaning-services",
    domainId: "dispatch",
    title: "ACS crew route and ETA snapshot",
    entityKind: "dispatch_snapshot",
    lifecycleStage: "Planned -> En route proof needed",
    status: "read-only",
    sourceFlowId: "acs-public-quote-to-root-dispatch",
    sourceSystem: "ACS crew portal GPS + Root dispatch contract",
    dataSource: "static_recovery_contract",
    owner: "Dispatch",
    route: "/admin/dispatch",
    amountLabel: null,
    facts: [
      "Dispatch owns route truth, not public booking or generic scheduling.",
      "Crew portal posts GPS pings; ROOT dispatch consumes route plans, locations, geofence, and ETA state.",
      "Stale ping, next stop, delay, and geofence state need to render before customer messaging exists.",
    ],
    mutationGates: ["start GPS capture", "dispatch crew", "send ETA", "override route", "mark onsite"],
    nextAction: "Create the ACS dispatch read adapter over crew assignments, route plans, job_locations, ETA, and geofence events.",
    blocker: "Live location capture and customer ETA messages are disabled until permissioned mobile/event persistence is canonical.",
  },
  {
    id: "readmodel-cco-cross-app-project",
    accountId: "content-co-op",
    domainId: "project",
    title: "CCO brief to Co-* project spine",
    entityKind: "project",
    lifecycleStage: "Project adapter missing",
    status: "adapter-needed",
    sourceFlowId: "cco-brief-to-commercial-project-delivery",
    sourceSystem: "Co-Script + Co-Cut + Co-Deliver schemas",
    dataSource: "static_recovery_contract",
    owner: "CCO Delivery",
    route: "/admin/files",
    amountLabel: null,
    facts: [
      "A single cross-app project id must carry brief, estimate, script, edit, review, delivery, and billing follow-up.",
      "Co-* apps stay specialist authorities launched from project context.",
      "Mission Control owns rollups, links, approvals, blockers, and next action.",
    ],
    mutationGates: ["create Co-Produce context", "create Co-Cut project", "create Co-Deliver package", "approve delivery"],
    nextAction: "Define the shared project adapter id and render Co-* launch/read rollups from that spine.",
    blocker: "No proven shared cross-app project key.",
  },
];

export const MISSION_VALUE_LOOPS: MissionValueLoop[] = [
  {
    id: "value-loop-quote-proposal",
    accountId: null,
    title: "Quote and proposal authority",
    status: "active",
    metric: "Deal shaping",
    proof: "Legacy ROOT quote workflow defines draft, approval, send, outcome, and invoice conversion.",
    nextAction: "Open the quote workspace before quote, proposal, or pricing logic is simplified.",
    route: "/admin/quotes",
  },
  {
    id: "value-loop-invoice-authority",
    accountId: null,
    title: "Invoice authority",
    status: "active",
    metric: "Collectable work",
    proof: "Legacy ROOT invoice workflow separates issue, payment, reminders, finance, reconciliation, and archive.",
    nextAction: "Open the invoice workspace when the record is billable instead of negotiable.",
    route: "/admin/invoices",
  },
  {
    id: "value-loop-dispatch-control",
    accountId: "astro-cleaning-services",
    title: "Dispatch control",
    status: "active",
    metric: "Crew movement",
    proof: "Legacy ROOT dispatch contract defines route, next stop, ETA, stale ping, geofence, and delay state.",
    nextAction: "Use dispatch for live route truth; use scheduling for planning and assignment.",
    route: "/admin/dispatch",
  },
  {
    id: "value-loop-acs-cash",
    accountId: "astro-cleaning-services",
    title: "ACS cash path",
    status: "active",
    metric: "Quote to job",
    proof: "Local ACS handoff and readiness-blocked job candidate are visible.",
    nextAction: "Convert quote, resolve readiness, schedule service, then create invoice follow-up.",
    route: "/admin/inbox",
  },
  {
    id: "value-loop-acs-readiness",
    accountId: "astro-cleaning-services",
    title: "ACS readiness guardrail",
    status: "active",
    metric: "Dispatch safety",
    proof: "Crew readiness blocker prevents blind assignment.",
    nextAction: "Use Jobs and Scheduling to keep readiness before dispatch.",
    route: "/admin/jobs",
  },
  {
    id: "value-loop-cco-delivery",
    accountId: "content-co-op",
    title: "CCO delivery path",
    status: "queued",
    metric: "Brief to delivery",
    proof: "Creative brief handoff converts to project and approval artifacts locally.",
    nextAction: "Route brief through opportunity, project, approvals, delivery, and billing follow-up.",
    route: "/admin/inbox?account=content-co-op",
  },
  {
    id: "value-loop-runtime-proof",
    accountId: null,
    title: "Runtime proof ledger",
    status: "blocked",
    metric: "Local proof",
    proof: "Mission Control is healthy; donor lanes expose exact blockers.",
    nextAction: "Unblock donor installs only after explicit approval, starting with ACS and onboarding.",
    route: "/admin/runtime",
  },
  {
    id: "value-loop-video-production",
    accountId: "content-co-op",
    title: "Video production path",
    status: "active",
    metric: "Brief to delivery",
    proof: "Aether Video OS unifies project context, research, editing, and publishing in one shell.",
    nextAction: "Create project, run viral research, assign agent tasks, track assets, and publish from the Video OS workspace.",
    route: "/admin/video",
  },
  {
    id: "value-loop-video-research",
    accountId: "content-co-op",
    title: "Viral research loop",
    status: "active",
    metric: "Hook discovery",
    proof: "Sandcastles-style outlier analysis generates data-backed hooks and script drafts.",
    nextAction: "Run Co-Script research agent against niche keywords, review outliers, and convert top hooks into script candidates.",
    route: "/admin/video/research",
  },
];

export const MISSION_AGENT_LANES: MissionAgentLane[] = [
  {
    id: "agent-lane-codex-patch",
    title: "Codex patch",
    status: "active",
    authority: "Code changes plus verification",
    guardrail: "No production mutation without approval.",
    nextAction: "Patch, typecheck, test when writable, and browser-check local paths.",
    route: "/admin/packets",
  },
  {
    id: "agent-lane-browser-proof",
    title: "Browser proof",
    status: "active",
    authority: "Visual and click verification",
    guardrail: "Safe navigation only; no submit, upload, payment, or logout without approval.",
    nextAction: "Verify dashboard, inbox, jobs, runtime, health, and packet paths after each pass.",
    route: "/admin/health",
  },
  {
    id: "agent-lane-connectors",
    title: "Connectors",
    status: "queued",
    authority: "Gmail, Drive, Calendar, GitHub, Stripe, and future app context",
    guardrail: "Reading can inform work; sending, sharing, uploading, or sensitive typing requires confirmation.",
    nextAction: "Use connector context only when it advances a specific value loop.",
    route: "/admin/inbox",
  },
  {
    id: "agent-lane-memory-canon",
    title: "Memory and canon",
    status: "active",
    authority: "Prior decisions, rollout history, and repo boundaries",
    guardrail: "Memory can guide recovery but must be verified when drift risk is high.",
    nextAction: "Keep product name, source-of-truth map, freeze list, and parked signals aligned.",
    route: "/admin/runtime",
  },
  {
    id: "agent-lane-co-producer",
    title: "Co-Producer",
    status: "active",
    authority: "Project planning, brief analysis, and production setup",
    guardrail: "Agent can plan and estimate; human approves scope and budget.",
    nextAction: "Assign to projects needing brief-to-timeline conversion, crew booking, and deliverable scoping.",
    route: "/admin/video",
  },
  {
    id: "agent-lane-co-scripter",
    title: "Co-Scripter",
    status: "active",
    authority: "Viral research, outlier analysis, and script generation",
    guardrail: "Agent can research and draft; human validates facts and brand voice.",
    nextAction: "Run niche research, extract outliers, score hooks, and generate script drafts for operator review.",
    route: "/admin/video/research",
  },
  {
    id: "agent-lane-co-editor",
    title: "Co-Editor",
    status: "queued",
    authority: "Auto-cut, caption, reframe, and virality scoring",
    guardrail: "Agent can generate candidates; human selects final cuts and approves exports.",
    nextAction: "Dispatch auto-cut tasks after raw footage is uploaded. Generate captions, reframes, and thumbnail options.",
    route: "/admin/video/edit",
  },
  {
    id: "agent-lane-co-deliverer",
    title: "Co-Deliverer",
    status: "queued",
    authority: "Multi-platform publishing, scheduling, and analytics rollup",
    guardrail: "Agent can draft packages and schedule; human confirms before publish.",
    nextAction: "Create platform-specific packages, schedule posts, and collect performance analytics into Video OS dashboard.",
    route: "/admin/video/deliver",
  },
];

export const MISSION_ROLLOUTS: MissionRollout[] = [
  MEGA_VALUE_PLAN_12,
  MEGA_VALUE_PLAN_11,
  MEGA_VALUE_PLAN_10,
  MEGA_VALUE_PLAN_9,
  MEGA_VALUE_PLAN_8,
  MEGA_VALUE_PLAN_7,
  MEGA_VALUE_PLAN_5,
  MEGA_ROLLOUT_4,
];
export const ACTIVE_MISSION_ROLLOUT = MEGA_VALUE_PLAN_11;

export const RUNTIME_SURFACES: RuntimeSurface[] = [
  {
    id: "mission-control-shell",
    label: "Mission Control shell",
    port: 4300,
    path: "/Users/baileyeubanks/Downloads/root-os-_-mission-control",
    authorityClass: "canonical-shell",
    status: "canonical",
    command: "PORT=4300 npm run dev",
    health: "http://127.0.0.1:4300/api/health",
    notes: "Canonical shell candidate with packet runtime and Mission Control contract endpoints.",
    sharedPortGroup: null,
  },
  {
    id: "acs-module-demo",
    label: "ACS module/demo",
    port: 4301,
    path: "/Users/baileyeubanks/Downloads/mission-control---acs-admin",
    authorityClass: "module-demo-donor",
    status: "extract",
    command: "PORT=4301 npm run dev",
    health: "http://127.0.0.1:4301/api/adminDashboard",
    notes: "ACS admin donor only; not the shell.",
    sharedPortGroup: null,
  },
  {
    id: "cross-business-root-2-donor",
    label: "root-2 cross-business donor",
    port: 4302,
    path: "/Users/baileyeubanks/Downloads/root-2",
    authorityClass: "business-model-donor",
    status: "extract",
    command: "PORT=4302 npm run dev",
    health: "http://127.0.0.1:4302/api/health",
    notes: "Rich cross-business donor; Root branding is not canonical.",
    sharedPortGroup: null,
  },
  {
    id: "co-produce",
    label: "Co-Produce donor",
    port: 4303,
    path: "/Users/baileyeubanks/Downloads/co-produce",
    authorityClass: "module-demo-donor",
    status: "extract",
    command: "PORT=4303 npm run dev",
    health: "http://127.0.0.1:4303",
    notes: "Workflow donor for brief-to-production setup.",
    sharedPortGroup: "co-produce-lane",
  },
  {
    id: "co-produce-intelligence",
    label: "Co-Produce intelligence donor",
    port: 4303,
    path: "/Users/baileyeubanks/Downloads/co-produce-2",
    authorityClass: "module-demo-donor",
    status: "extract",
    command: "PORT=4303 npm run dev",
    health: "http://127.0.0.1:4303",
    notes: "Shares 4303; do not run simultaneously with co-produce.",
    sharedPortGroup: "co-produce-lane",
  },
  {
    id: "co-deliver-branded",
    label: "Co-Deliver branded donor",
    port: 4304,
    path: "/Users/baileyeubanks/Downloads/co-deliver",
    authorityClass: "module-demo-donor",
    status: "extract",
    command: "PORT=4304 npm run dev",
    health: "http://127.0.0.1:4304",
    notes: "Branded review/delivery UX donor.",
    sharedPortGroup: "co-deliver-lane",
  },
  {
    id: "co-deliver-backend",
    label: "Co-Deliver video review backend donor",
    port: 4304,
    path: "/Users/baileyeubanks/Downloads/video-review-platform-5",
    authorityClass: "backend-donor",
    status: "extract",
    command: "PORT=4304 npm run dev",
    health: "http://127.0.0.1:4304",
    notes: "Shares 4304; inspect policies before schema adoption.",
    sharedPortGroup: "co-deliver-lane",
  },
  {
    id: "acs-onboarding",
    label: "ACS onboarding",
    port: 4305,
    path: "/Users/baileyeubanks/Downloads/astro-cleaning-onboarding",
    authorityClass: "supporting-subsystem",
    status: "extract",
    command: "PORT=4305 npm run dev",
    health: "http://127.0.0.1:4305",
    notes: "Crew readiness/certification donor.",
    sharedPortGroup: null,
  },
  {
    id: "hermes-concierge",
    label: "Hermes Concierge/widget",
    port: 4306,
    path: "/Users/baileyeubanks/Downloads/hermes-concierge",
    authorityClass: "parked",
    status: "parked",
    command: "PORT=4306 npm run dev",
    health: "http://127.0.0.1:4306/api/health",
    notes: "Parked widget donor; Hermes is not authority.",
    sharedPortGroup: null,
  },
  {
    id: "platform-relief",
    label: "Platform Relief",
    port: 4317,
    path: "/Users/baileyeubanks/Downloads/platform-relief",
    authorityClass: "parked",
    status: "preserve",
    command: "PORT=4317 npm run dev",
    health: "http://127.0.0.1:4317/api/health",
    notes: "Separate product candidate; do not merge into Mission Control.",
    sharedPortGroup: null,
  },
];

export function getServicePosture(packetServiceEnabled: boolean): ServicePosture {
  return {
    supabase: hasEnvKey("SUPABASE_URL") && hasEnvKey("SUPABASE_SERVICE_ROLE_KEY") ? "configured" : "missing_config",
    twilio: hasEnvKey("TWILIO_ACCOUNT_SID") && hasEnvKey("TWILIO_AUTH_TOKEN") && hasEnvKey("TWILIO_PHONE_NUMBER") ? "configured" : "missing_config",
    gemini: hasEnvKey("GEMINI_API_KEY") || hasEnvKey("GOOGLE_API_KEY") || isGeminiCliAvailable() ? "configured" : "missing_config",
    packets: packetServiceEnabled ? "enabled" : "missing_config",
    hermes: "peripheral",
    paperclip: "optional",
  };
}

export function getMissionControlBootstrap(packetServiceEnabled: boolean): MissionControlBootstrap {
  return {
    data_source: "static_recovery_contract",
    generated_at: new Date().toISOString(),
    product: {
      name: "Mission Control",
      canonicalShellPath: "/Users/baileyeubanks/Downloads/root-os-_-mission-control",
      rootStatus: "legacy-donor-contract-label",
      deploymentStatus: "local-recovery-only",
    },
    services: getServicePosture(packetServiceEnabled),
    accounts: COMPANY_ACCOUNTS,
    modules: MISSION_MODULES,
    tasks: MISSION_TASKS,
    approvals: APPROVAL_REQUESTS,
    events: BUSINESS_EVENTS,
    runtimes: RUNTIME_SURFACES,
    rollout: ACTIVE_MISSION_ROLLOUT,
    rollouts: MISSION_ROLLOUTS,
    valueLoops: MISSION_VALUE_LOOPS,
    agentLanes: MISSION_AGENT_LANES,
    operatingDomains: MISSION_OPERATING_DOMAINS,
    integrationFlows: MISSION_INTEGRATION_FLOWS,
    adapterGaps: MISSION_ADAPTER_GAPS,
    readModels: MISSION_READ_MODELS,
  };
}
